/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import Service.UserService;
import java.awt.CardLayout;
import java.awt.Image;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/**
 *
 * @author Admin
 */
public class panelCaiDat extends javax.swing.JPanel {

    private cardThongTin cardThongTin;
    private cardDoiMatKhau cardDoiMatKhau;
    private cardGiaoDien cardGiaoDien;

    public panelCaiDat(int userId) {
        initComponents();
        setupIcon();
        
        UserService userService = new UserService();
        cardThongTin = new cardThongTin(userService, userId);
        cardDoiMatKhau = new cardDoiMatKhau();
        cardGiaoDien = new cardGiaoDien();
       
        
        panelCard.setLayout(new java.awt.CardLayout());
        panelCard.add(cardThongTin, "cardThongTin");
        panelCard.add(cardDoiMatKhau, "cardDoiMatKhau");
        panelCard.add(cardGiaoDien, "cardGiaoDien");

        btnThongTin.addActionListener(e -> {
            CardLayout cl = (CardLayout) panelCard.getLayout();
            cl.show(panelCard, "cardThongTin");
        });
        btnDoiMatKhau.addActionListener(e -> {
            CardLayout cl = (CardLayout) panelCard.getLayout();
            cl.show(panelCard, "cardDoiMatKhau");
        });

        btnGiaoDien.addActionListener(e -> {
            CardLayout cl = (CardLayout) panelCard.getLayout();
            cl.show(panelCard, "cardGiaoDien");
        });
    }
    
    private void setupIcon() {
        resizeIcon(btnThongTin, "/resources/user.png");
        resizeIcon(btnDoiMatKhau, "/resources/locked.png");
        resizeIcon(btnGiaoDien, "/resources/interface.png");
    }

    private void resizeIcon(JButton btn, String path) {
        try {
            // Debug: In ra đường dẫn
            System.out.println("Đang tìm icon: " + path);

            URL iconURL = getClass().getResource(path);

            if (iconURL == null) {
                System.err.println("KHÔNG TÌM THẤY: " + path);
                System.err.println("Thử tìm với path khác:");

                // Thử các cách khác
                iconURL = getClass().getResource("/" + path);
                if (iconURL != null) System.out.println("Tìm thấy với: /" + path);

                iconURL = getClass().getClassLoader().getResource(path);
                if (iconURL != null) System.out.println("Tìm thấy với ClassLoader: " + path);

                return; // Dừng nếu không tìm thấy
            }

            System.out.println("Tìm thấy icon tại: " + iconURL);

            ImageIcon originalIcon = new ImageIcon(iconURL);
            Image img = originalIcon.getImage();
            Image scaledImg = img.getScaledInstance(32, 32, Image.SCALE_SMOOTH);
            btn.setIcon(new ImageIcon(scaledImg));

        } catch (Exception e) {
            System.err.println("Lỗi khi load icon: " + path);
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        btnThongTin = new javax.swing.JButton();
        btnGiaoDien = new javax.swing.JButton();
        btnDoiMatKhau = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        panelCard = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setDoubleBuffered(false);
        setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        btnThongTin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThongTin.setText("Thông tin tài khoản ");
        btnThongTin.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        btnGiaoDien.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGiaoDien.setText("Cấu hình giao diện ");
        btnGiaoDien.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        btnDoiMatKhau.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDoiMatKhau.setText("Đổi mật khẩu ");
        btnDoiMatKhau.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitle.setText("CÀI ĐẶT THÔNG TIN HỆ THỐNG ");

        panelCard.setBackground(new java.awt.Color(255, 255, 255));
        panelCard.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        panelCard.setPreferredSize(new java.awt.Dimension(800, 400));

        javax.swing.GroupLayout panelCardLayout = new javax.swing.GroupLayout(panelCard);
        panelCard.setLayout(panelCardLayout);
        panelCardLayout.setHorizontalGroup(
            panelCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelCardLayout.setVerticalGroup(
            panelCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnGiaoDien, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDoiMatKhau, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnThongTin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(panelCard, javax.swing.GroupLayout.DEFAULT_SIZE, 834, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 259, Short.MAX_VALUE)
                .addComponent(lblTitle)
                .addGap(398, 398, 398))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnThongTin, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDoiMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGiaoDien, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 249, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelCard, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
                        .addContainerGap())))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDoiMatKhau;
    private javax.swing.JButton btnGiaoDien;
    private javax.swing.JButton btnThongTin;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel panelCard;
    // End of variables declaration//GEN-END:variables
}
