/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import DAO.DoanChatDAO;
import DAO.TinNhanDAO;
import Model.DoanChat;
import Model.TinNhan;
import Service.AIActionHandler;
import Service.GeminiService;
import Service.ThongKeService;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.event.FocusEvent;
import javax.swing.BorderFactory;
import javax.swing.DefaultListCellRenderer;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JCheckBoxMenuItem;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JMenuItem;
import javax.swing.JPanel;
import javax.swing.JPopupMenu;
import javax.swing.SwingConstants;
import java.awt.Container;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Toolkit;
import java.awt.datatransfer.StringSelection;
import java.awt.event.FocusAdapter;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JOptionPane;
import javax.swing.JScrollBar;
import javax.swing.JScrollPane;
import javax.swing.JTextPane;
import javax.swing.SwingUtilities;
import com.google.gson.JsonObject;
import javax.swing.ListModel;

/**
 *
 * @author Nam
 */
public class panelChatbot extends javax.swing.JPanel {

    private final Color SIDEBAR_BG = Color.WHITE;
    private final Color SIDEBAR_HOVER = new Color(245, 246, 247);
    private final Color SIDEBAR_SELECTED = new Color(230, 232, 235);
    private final Color TEXT_COLOR = new Color(50, 50, 50);
    private final Color TEXT_MUTED = new Color(120, 120, 120);
    private final Color USER_MSG_BG = new Color(236, 240, 245);
    private final Color AI_MSG_BG = new Color(255, 255, 255);
    
    private DefaultListModel<DoanChat> chatListModel;
    private JPanel chatContainer;
    private JScrollPane chatScrollPane;

    private int currentChatId = -1;

    private DoanChatDAO doanChatDAO;
    private TinNhanDAO tinNhanDAO;
    private GeminiService geminiService;
    private AIActionHandler actionHandler;
    private int currentUserId = 2;
    private ThongKeService thongKeService;


    /**
     * Creates new form panelChatbot
     */
    public panelChatbot() throws ClassNotFoundException {
        initComponents();
        setupServices();
        setupSidebarUI();
        setupHeaderUI();
        setupHeaderMenu();
        setupListClickEvent();
        javax.swing.SwingUtilities.invokeLater(() -> {
        jLabel2.setFont(
            jLabel2.getFont().deriveFont(Font.BOLD)
        );
    });      
        setupInputUI();
        setupChatArea();
        
        // Load dữ liệu
        taiDanhSachDoanChat();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("jCheckBoxMenuItem2");

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(895, 590));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel1MouseExited(evt);
            }
        });

        jToolBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jToolBar1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jToolBar1.setRollover(true);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Chatbot.png"))); // NOI18N
        jLabel1.setText("Trợ lí AI");
        jLabel1.setPreferredSize(new java.awt.Dimension(270, 50));
        jToolBar1.add(jLabel1);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jToolBar1.add(jScrollPane1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 649, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/3cham.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel2.setText("Đoạn chat mới");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(23, 23, 23))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 679, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Ảnh chụp màn hình 2025-12-19 220850.png"))); // NOI18N
        jButton3.setBorder(null);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane4.setViewportView(jTextArea2);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addGap(20, 20, 20))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents
private void setupSidebarUI() {
    jPanel1.setBackground(SIDEBAR_BG);

    /* ===== TOOLBAR ===== */
    jToolBar1.removeAll();
    jToolBar1.setOrientation(SwingConstants.VERTICAL);
    jToolBar1.setLayout(new BoxLayout(jToolBar1, BoxLayout.Y_AXIS));
    jToolBar1.setBackground(SIDEBAR_BG);
    jToolBar1.setBorder(BorderFactory.createEmptyBorder(10, 8, 10, 8));

    /* ===== HEADER: ICON + TRỢ LÍ AI ===== */
    JPanel headerPanel = new JPanel(new BorderLayout(8, 0));
    headerPanel.setBackground(SIDEBAR_BG);
    headerPanel.setBorder(BorderFactory.createEmptyBorder(0, 12, 10, 12));
    headerPanel.setMaximumSize(new Dimension(Integer.MAX_VALUE, 50));
    headerPanel.setAlignmentX(Component.LEFT_ALIGNMENT);

    JLabel iconLabel = new JLabel(
        new ImageIcon(getClass().getResource("/resources/Chatbot.png"))
    );

    JLabel titleLabel = new JLabel("Trợ lí AI");
    titleLabel.setFont(new Font("Segoe UI", Font.BOLD, 15));
    titleLabel.setForeground(TEXT_COLOR);

    headerPanel.add(iconLabel, BorderLayout.WEST);
    headerPanel.add(titleLabel, BorderLayout.CENTER);

    jToolBar1.add(headerPanel);

    /* ===== NÚT + ĐOẠN CHAT MỚI (NGAY DƯỚI HEADER) ===== */
    JLabel newChatBtn = new JLabel("+ Đoạn chat mới", SwingConstants.LEFT);
    newChatBtn.setFont(new Font("Segoe UI", Font.BOLD, 14));
    newChatBtn.setOpaque(true);
    newChatBtn.setBackground(SIDEBAR_BG);
    newChatBtn.setForeground(TEXT_COLOR);
    newChatBtn.setBorder(BorderFactory.createCompoundBorder(
        BorderFactory.createLineBorder(new Color(200, 200, 200)),
        BorderFactory.createEmptyBorder(8, 12, 8, 12)
    ));
    
    newChatBtn.setMaximumSize(new Dimension(Integer.MAX_VALUE, 40));
    newChatBtn.setAlignmentX(Component.LEFT_ALIGNMENT);
    newChatBtn.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

    newChatBtn.addMouseListener(new MouseAdapter() {
        @Override
        public void mouseClicked(MouseEvent e) {
            try {
                taoDoanChatMoi();
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }

        @Override
        public void mouseEntered(MouseEvent e) {
            newChatBtn.setBackground(SIDEBAR_HOVER);
        }

        @Override
        public void mouseExited(MouseEvent e) {
            newChatBtn.setBackground(SIDEBAR_BG);
        }
    });

    jToolBar1.add(newChatBtn);

    jToolBar1.add(Box.createVerticalStrut(10)); // khoảng cách

    /* ===== DANH SÁCH ĐOẠN CHAT ===== */
        chatListModel = new DefaultListModel<>();
        jList1.setModel((ListModel) chatListModel);
        ((JList) jList1).setModel(chatListModel);

    jList1.setBackground(SIDEBAR_BG);
    jList1.setForeground(TEXT_COLOR);
    jList1.setFont(new Font("Segoe UI", Font.PLAIN, 13));
    jList1.setSelectionBackground(SIDEBAR_SELECTED);
    jList1.setFixedCellHeight(42);
    jList1.setBorder(BorderFactory.createEmptyBorder(5, 5, 5, 5));

    jList1.setCellRenderer(new DefaultListCellRenderer() {
        @Override
        public Component getListCellRendererComponent(
                JList<?> list, Object value, int index,
                boolean isSelected, boolean cellHasFocus) {

            JLabel label = (JLabel) super.getListCellRendererComponent(
                    list, value, index, isSelected, cellHasFocus);

            if (value instanceof DoanChat dc) {
                label.setText(dc.isLaGhim()
                        ? "📌 " + dc.getTieuDe()
                        : dc.getTieuDe());
            }

            label.setBorder(BorderFactory.createEmptyBorder(8, 12, 8, 12));
            return label;
        }
    });

    jScrollPane1.setBorder(null);
    jScrollPane1.getViewport().setBackground(SIDEBAR_BG);
    jScrollPane1.setAlignmentX(Component.LEFT_ALIGNMENT);

    jToolBar1.add(jScrollPane1);

    jToolBar1.revalidate();
    jToolBar1.repaint();
}


 private void setupHeaderUI() {
        jPanel2.setBackground(Color.WHITE);
        jPanel2.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, new Color(230, 230, 230)));
        jLabel2.setFont(new Font("Segoe UI", Font.BOLD, 15));
        jLabel2.setForeground(new Color(40, 40, 40));
    }

private void setupListClickEvent() {
        jList1.addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                DoanChat selected = (DoanChat) ((JList) jList1).getSelectedValue();
                if (selected != null) {
                    currentChatId = selected.getId();
                    jLabel2.setText(selected.getTieuDe());
                    try {
                        taiTinNhan(currentChatId);
                    } catch (ClassNotFoundException ex) {
                        System.getLogger(panelChatbot.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
                    }
                }
            }
        });
    }


private void setupHeaderMenu() {
        jPopupMenu1 = new JPopupMenu();
        jPopupMenu1.setBackground(Color.WHITE);
        jPopupMenu1.setBorder(BorderFactory.createLineBorder(new Color(220, 220, 220)));

        Font menuFont = new Font("Segoe UI", Font.PLAIN, 13);

        jCheckBoxMenuItem1 = new JCheckBoxMenuItem("Ghim đoạn chat");
        jCheckBoxMenuItem2 = new JCheckBoxMenuItem("Lưu trữ đoạn chat");
        JMenuItem renameItem = new JMenuItem("Sửa tiêu đề");
        JMenuItem deleteItem = new JMenuItem("Xóa đoạn chat");

        for (JMenuItem item : new JMenuItem[]{jCheckBoxMenuItem1, jCheckBoxMenuItem2, renameItem, deleteItem}) {
            item.setFont(menuFont);
            item.setBackground(Color.WHITE);
        }

        jPopupMenu1.add(jCheckBoxMenuItem1);
        jPopupMenu1.add(jCheckBoxMenuItem2);
        jPopupMenu1.addSeparator();
        jPopupMenu1.add(renameItem);
        jPopupMenu1.addSeparator();
        jPopupMenu1.add(deleteItem);

        jButton2.addActionListener(e -> jPopupMenu1.show(jButton2, 0, jButton2.getHeight()));

        jCheckBoxMenuItem1.addActionListener(e -> {
            try {
                ghimDoanChat();
            } catch (ClassNotFoundException ex) {
                System.getLogger(panelChatbot.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
        });
        renameItem.addActionListener(e -> {
            try {
                suaTieuDe();
            } catch (ClassNotFoundException ex) {
                System.getLogger(panelChatbot.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
        });
        deleteItem.addActionListener(e -> {
            try {
                xoaDoanChat();
            } catch (ClassNotFoundException ex) {
                System.getLogger(panelChatbot.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
        });
    }


 private void renameChat() {
    int index = jList1.getSelectedIndex();
    if (index == -1) return;

    String oldName = jList1.getSelectedValue();
    String newName = javax.swing.JOptionPane.showInputDialog(
            this,
            "Nhập tiêu đề mới:",
            oldName
    );

    if (newName != null && !newName.trim().isEmpty()) {
        DefaultListModel<String> model =
                (DefaultListModel<String>) jList1.getModel();
        model.set(index, newName.trim());
        jLabel2.setText(newName.trim());
    }
}

 private void deleteChat() {
    int index = jList1.getSelectedIndex();
    if (index == -1) return;

    int confirm = javax.swing.JOptionPane.showConfirmDialog(
            this,
            "Bạn có chắc muốn xóa đoạn chat này?",
            "Xác nhận",
            javax.swing.JOptionPane.YES_NO_OPTION
    );

    if (confirm == javax.swing.JOptionPane.YES_OPTION) {
        DefaultListModel<String> model =
                (DefaultListModel<String>) jList1.getModel();
        model.remove(index);

        jLabel2.setText("Đoạn chat mới");
    }
}

 private void setupInputUI() {
        jPanel4.setLayout(new BorderLayout(10, 0));
        jPanel4.setBackground(Color.WHITE);
        jPanel4.setBorder(BorderFactory.createCompoundBorder(
            BorderFactory.createLineBorder(new Color(220, 220, 220)),
            BorderFactory.createEmptyBorder(8, 12, 8, 12)
        ));

        jTextArea2.setText("Hỏi gì đó về chi tiêu của bạn...");
        jTextArea2.setForeground(Color.GRAY);
        jTextArea2.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        jTextArea2.setRows(2);
        jTextArea2.setLineWrap(true);
        jTextArea2.setWrapStyleWord(true);
        jTextArea2.setBorder(null);

        jScrollPane4.setBorder(null);
        jScrollPane4.getViewport().setOpaque(false);

        jButton3.setBorder(BorderFactory.createEmptyBorder(6, 10, 6, 10));
        jButton3.addActionListener(e -> {
            try {
                guiTinNhan();
            } catch (ClassNotFoundException ex) {
                System.getLogger(panelChatbot.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
        });

        jPanel4.removeAll();
        jPanel4.add(jScrollPane4, BorderLayout.CENTER);
        jPanel4.add(jButton3, BorderLayout.EAST);

        // Enter để gửi
        jTextArea2.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER && !e.isShiftDown()) {
                    e.consume();
                    try {
                        guiTinNhan();
                    } catch (ClassNotFoundException ex) {
                        System.getLogger(panelChatbot.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
                    }
                }
            }
        });

        // Placeholder
        jTextArea2.addFocusListener(new FocusAdapter() {
            @Override
            public void focusGained(FocusEvent e) {
                if (jTextArea2.getText().equals("Hỏi gì đó về chi tiêu của bạn...")) {
                    jTextArea2.setText("");
                    jTextArea2.setForeground(Color.BLACK);
                }
            }

            @Override
            public void focusLost(FocusEvent e) {
                if (jTextArea2.getText().isEmpty()) {
                    jTextArea2.setText("Hỏi gì đó về chi tiêu của bạn...");
                    jTextArea2.setForeground(Color.GRAY);
                }
            }
        });
    }
    public panelChatbot(int userId) throws ClassNotFoundException {
        this();
        this.currentUserId = userId;
        taiDanhSachDoanChat();
    }
    
    private void setupServices() {
        doanChatDAO = new DoanChatDAO();
        tinNhanDAO = new TinNhanDAO();
        geminiService = new GeminiService();
        actionHandler = new AIActionHandler();
        thongKeService = new ThongKeService();
    }
    
private void setupChatArea() {
        chatContainer = new JPanel();
        chatContainer.setLayout(new BoxLayout(chatContainer, BoxLayout.Y_AXIS));
        chatContainer.setBackground(Color.WHITE);
        chatContainer.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
        
        chatScrollPane = new JScrollPane(chatContainer);
        chatScrollPane.setBorder(null);
        chatScrollPane.getVerticalScrollBar().setUnitIncrement(16);
        
        jPanel3.setLayout(new BorderLayout());
        jPanel3.add(chatScrollPane, BorderLayout.CENTER);
        
        chatContainer.addComponentListener(new java.awt.event.ComponentAdapter() {
        @Override
        public void componentResized(java.awt.event.ComponentEvent e) {
            chatContainer.revalidate();
            chatContainer.repaint();
        }
    });
    }

private void taiDanhSachDoanChat() throws ClassNotFoundException {
        chatListModel.clear();
        List<DoanChat> list = doanChatDAO.layDanhSachDoanChat(currentUserId);
        for (DoanChat dc : list) {
            chatListModel.addElement(dc);
        }
    }
    
    private void taoDoanChatMoi() throws ClassNotFoundException {
        DoanChat newChat = new DoanChat(currentUserId, "Đoạn chat mới");
        int id = doanChatDAO.themDoanChat(newChat);
        
        if (id > 0) {
            newChat.setId(id);
            chatListModel.insertElementAt(newChat, 0);
            jList1.setSelectedIndex(0);
            currentChatId = id;
            jLabel2.setText("Đoạn chat mới");
            chatContainer.removeAll();
            chatContainer.revalidate();
            chatContainer.repaint();
        }
    }
    
    private void taiTinNhan(int doanChatId) throws ClassNotFoundException {
        chatContainer.removeAll();
        
        List<TinNhan> messages = tinNhanDAO.layTinNhanTheoDoanChat(doanChatId);
        
        for (TinNhan msg : messages) {
            themTinNhanVaoGiaoDien(msg);
        }
        
        chatContainer.revalidate();
        chatContainer.repaint();
        
        // Scroll xuống cuối
        SwingUtilities.invokeLater(() -> {
            JScrollBar vertical = chatScrollPane.getVerticalScrollBar();
            vertical.setValue(vertical.getMaximum());
        });
    }
    
    private void guiTinNhan() throws ClassNotFoundException {
    String text = jTextArea2.getText().trim();
    
    if (text.isEmpty() || text.equals("Hỏi gì đó về chi tiêu của bạn...")) {
        return;
    }
    
    // Tạo chat mới nếu chưa có
    if (currentChatId == -1) {
        taoDoanChatMoi();
    }
    
    // Lưu tin nhắn người dùng
    TinNhan userMsg = new TinNhan(currentChatId, TinNhan.VaiTro.USER, text);
    int msgId = tinNhanDAO.themTinNhan(userMsg);
    userMsg.setId(msgId);
    
    // Hiển thị
    themTinNhanVaoGiaoDien(userMsg);
    jTextArea2.setText("");
    
    // Tạo tiêu đề tự động
    if (tinNhanDAO.demTinNhan(currentChatId) == 1) {
        taoTieuDeTuDong(text);
    }
    
    // Gọi AI trong thread riêng
new Thread(() -> {
    try {
        List<TinNhan> history =
            tinNhanDAO.layTinNhanTheoDoanChat(currentChatId);

        // 👉 1. JAVA THỐNG KÊ TRƯỚC
        String thongKe = thongKeService.thongKeChiTieu(
                currentUserId, text
        );

        // 👉 2. AI CHỈ DIỄN ĐẠT
    String response = geminiService.sendMessage(
            history,
            thongKe + "\n\nHãy trình bày lại cho người dùng dễ hiểu.",
            currentUserId
    );

        TinNhan aiMsg = new TinNhan(
                currentChatId,
                TinNhan.VaiTro.ASSISTANT,
                response
        );
        int aiMsgId = tinNhanDAO.themTinNhan(aiMsg);
        aiMsg.setId(aiMsgId);

        SwingUtilities.invokeLater(() -> {
            themTinNhanVaoGiaoDien(aiMsg);
            xuLyActionTuAI(response);
        });

    } catch (Exception e) {
        e.printStackTrace();
    }
}).start();
}
    
    private void themTinNhanVaoGiaoDien(TinNhan msg) {
        JPanel msgPanel = new JPanel();
        msgPanel.setLayout(new BoxLayout(msgPanel, BoxLayout.Y_AXIS));
        msgPanel.setBackground(Color.WHITE);
        msgPanel.setBorder(BorderFactory.createEmptyBorder(5, 0, 5, 0));
        
        // Label tên
        JLabel nameLabel = new JLabel(msg.getVaiTro() == TinNhan.VaiTro.USER ? "Bạn" : "AI Assistant");
        nameLabel.setFont(new Font("Segoe UI", Font.BOLD, 12));
        nameLabel.setForeground(TEXT_MUTED);
        nameLabel.setAlignmentX(msg.getVaiTro() == TinNhan.VaiTro.USER ? Component.RIGHT_ALIGNMENT : Component.LEFT_ALIGNMENT);
        
        // Text pane cho nội dung
        JTextPane textPane = new JTextPane();
        textPane.setText(msg.getNoiDung());
        textPane.setEditable(false);
        textPane.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        textPane.setBackground(msg.getVaiTro() == TinNhan.VaiTro.USER ? USER_MSG_BG : AI_MSG_BG);
        textPane.setBorder(BorderFactory.createCompoundBorder(
            BorderFactory.createLineBorder(new Color(230, 230, 230)),
            BorderFactory.createEmptyBorder(10, 12, 10, 12)
        ));
        
        
        
        // Wrap panel
        JPanel wrapper = new JPanel(new FlowLayout(
            msg.getVaiTro() == TinNhan.VaiTro.USER ? FlowLayout.RIGHT : FlowLayout.LEFT, 0, 0
        ));
        wrapper.setBackground(Color.WHITE);
        wrapper.setMaximumSize(new Dimension(chatContainer.getWidth() - 40, Integer.MAX_VALUE));
        
        int maxWidth = Math.max(400, (int)(chatContainer.getWidth() * 0.7));
        textPane.setMaximumSize(new Dimension(maxWidth, Integer.MAX_VALUE));
        textPane.setPreferredSize(new Dimension(maxWidth, textPane.getPreferredSize().height));
        
        wrapper.add(textPane);
        
        msgPanel.add(nameLabel);
        msgPanel.add(Box.createVerticalStrut(5));
        msgPanel.add(wrapper);
        
        // Menu chuột phải
        taoMenuTinNhan(textPane, msg);
        
        chatContainer.add(msgPanel);
        chatContainer.revalidate();
        chatContainer.repaint();
        
        // Scroll xuống
        SwingUtilities.invokeLater(() -> {
            JScrollBar vertical = chatScrollPane.getVerticalScrollBar();
            vertical.setValue(vertical.getMaximum());
        });
    }
    
    private void taoMenuTinNhan(JTextPane textPane, TinNhan msg) {
        JPopupMenu contextMenu = new JPopupMenu();
        
        JMenuItem copyItem = new JMenuItem("Sao chép");
        JMenuItem editItem = new JMenuItem("Sửa");
        JMenuItem deleteItem = new JMenuItem("Xóa");
        
        copyItem.addActionListener(e -> {
            StringSelection selection = new StringSelection(msg.getNoiDung());
            Toolkit.getDefaultToolkit().getSystemClipboard().setContents(selection, null);
        });
        
        editItem.addActionListener(e -> {
            try {
                suaTinNhan(msg, textPane);
            } catch (ClassNotFoundException ex) {
                System.getLogger(panelChatbot.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
        });
        deleteItem.addActionListener(e -> {
            try {
                xoaTinNhan(msg);
            } catch (ClassNotFoundException ex) {
                System.getLogger(panelChatbot.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
        });
        
        contextMenu.add(copyItem);
        if (msg.getVaiTro() == TinNhan.VaiTro.USER) {
            contextMenu.add(editItem);
        }
        contextMenu.add(deleteItem);
        
        textPane.setComponentPopupMenu(contextMenu);
    }
    
private void xuLyActionTuAI(String response) {
    JsonObject action = geminiService.phanTichAction(response);
    
    if (action != null) {
        // Xử lý action
        AIActionHandler.ActionResult result = actionHandler.xuLyAction(action, currentUserId);
        
        SwingUtilities.invokeLater(() -> {
            if (result.isSuccess()) {
                JOptionPane.showMessageDialog(this,
                    result.getMessage(),
                    "Thành công",
                    JOptionPane.INFORMATION_MESSAGE);
                
                try {
                    // Reload context nếu cần
                    taiTinNhan(currentChatId);
                } catch (ClassNotFoundException ex) {
                    System.getLogger(panelChatbot.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
                }
            } else {
                JOptionPane.showMessageDialog(this,
                    result.getMessage(),
                    "Lỗi",
                    JOptionPane.ERROR_MESSAGE);
            }
        });
    }
}
    
    private void taoTieuDeTuDong(String tinNhanDauTien) {
        new Thread(() -> {
            try {
                String tieuDe = geminiService.taoTieuDeTuDong(tinNhanDauTien);
                
                if (tieuDe != null && !tieuDe.isEmpty()) {
                    doanChatDAO.capNhatTieuDe(currentChatId, tieuDe);
                    
                    SwingUtilities.invokeLater(() -> {
                        jLabel2.setText(tieuDe);
                        try {
                            taiDanhSachDoanChat();
                        } catch (ClassNotFoundException ex) {
                            System.getLogger(panelChatbot.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
                        }
                        
                        // Chọn lại chat hiện tại
                        for (int i = 0; i < chatListModel.size(); i++) {
                            if (chatListModel.get(i).getId() == currentChatId) {
                                jList1.setSelectedIndex(i);
                                break;
                            }
                        }
                    });
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }).start();
    }
    
    private void ghimDoanChat() throws ClassNotFoundException {
        if (currentChatId == -1) return;
        
        DoanChat current = doanChatDAO.layDoanChatTheoId(currentChatId);
        boolean newPinStatus = !current.isLaGhim();
        
        if (doanChatDAO.ghimDoanChat(currentChatId, newPinStatus)) {
            jCheckBoxMenuItem1.setSelected(newPinStatus);
            taiDanhSachDoanChat();
            
            // Chọn lại chat hiện tại
            for (int i = 0; i < chatListModel.size(); i++) {
                if (chatListModel.get(i).getId() == currentChatId) {
                    jList1.setSelectedIndex(i);
                    break;
                }
            }
        }
    }
    
    private void suaTieuDe() throws ClassNotFoundException {
        if (currentChatId == -1) return;
        
        String oldTitle = jLabel2.getText();
        String newTitle = JOptionPane.showInputDialog(this, "Nhập tiêu đề mới:", oldTitle);
        
        if (newTitle != null && !newTitle.trim().isEmpty()) {
            if (doanChatDAO.capNhatTieuDe(currentChatId, newTitle.trim())) {
                jLabel2.setText(newTitle.trim());
                taiDanhSachDoanChat();
            }
        }
    }
    
    private void xoaDoanChat() throws ClassNotFoundException {
        if (currentChatId == -1) return;
        
        int confirm = JOptionPane.showConfirmDialog(this,
            "Xóa đoạn chat sẽ xóa tất cả tin nhắn. Bạn có chắc?",
            "Xác nhận xóa",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE);
        
        if (confirm == JOptionPane.YES_OPTION) {
            if (doanChatDAO.xoaDoanChat(currentChatId)) {
                currentChatId = -1;
                jLabel2.setText("Đoạn chat mới");
                chatContainer.removeAll();
                chatContainer.revalidate();
                chatContainer.repaint();
                taiDanhSachDoanChat();
            }
        }
    }
    
    private void suaTinNhan(TinNhan msg, JTextPane textPane) throws ClassNotFoundException {
        String oldText = msg.getNoiDung();
        String newText = JOptionPane.showInputDialog(this, "Sửa tin nhắn:", oldText);
        
        if (newText != null && !newText.trim().isEmpty()) {
            if (tinNhanDAO.capNhatTinNhan(msg.getId(), newText.trim())) {
                msg.setNoiDung(newText.trim());
                textPane.setText(newText.trim());
            }
        }
    }
    
    private void xoaTinNhan(TinNhan msg) throws ClassNotFoundException {
        int confirm = JOptionPane.showConfirmDialog(this,
            "Bạn có chắc muốn xóa tin nhắn này?",
            "Xác nhận",
            JOptionPane.YES_NO_OPTION);
        
        if (confirm == JOptionPane.YES_OPTION) {
            if (tinNhanDAO.xoaTinNhan(msg.getId())) {
                taiTinNhan(currentChatId);
            }
        }
    }



    private void jPanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseEntered

    }//GEN-LAST:event_jPanel1MouseEntered

    private void jPanel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseExited

    }//GEN-LAST:event_jPanel1MouseExited

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
