/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Service.RegisterService;
import Service.RegisterService.RegisterResponse;
import Utils.HintUtils;
import java.awt.Image;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;

/**
 *
 * @author Admin
 */
public class RegisterFrame extends javax.swing.JFrame {

    private boolean showing = false; // trạng thái mật khẩu 
    private JLabel backgroundLabel;
    /**
     * Creates new form RegisterFrame
     */
    public RegisterFrame() {
        setUndecorated(true);
        initComponents();
        setLocationRelativeTo(null);
        setupLabelIcons(); 
        setupBackground();
        
        HintUtils.setHint(jtbEmail, "Nhập email...");
        HintUtils.setHint(jtbUser, "Nhập họ tên...");
        HintUtils.setHint(jpfPass, "Nhập mật khẩu...");
        
        // Sự kiện chuyển màn hình đăng ký 
        lblDangNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                // Tạo form đăng ký mới
                LoginFrame loginframe = new LoginFrame();
                loginframe.setVisible(true);

                // Ẩn form đăng nhập hiện tại
                RegisterFrame.this.setVisible(false);
            }

            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblDangNhap.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                lblDangNhap.setForeground(new java.awt.Color(65, 105, 255).brighter());
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblDangNhap.setForeground(new java.awt.Color(65, 105, 225));
            }
        });
        
        lblShowPass.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblShowPassMouseClicked(evt);
            }
        });
        
        btnDangKy.addActionListener(e -> {
            String fullName = jtbUser.getText().trim();
            String email = jtbEmail.getText().trim();
            String password = new String(jpfPass.getPassword()).trim();

            RegisterService regService = new RegisterService();
            RegisterResponse resp = regService.register(fullName, email, password);

            if (resp.result == RegisterService.RegisterResult.SUCCESS) {
                JOptionPane.showMessageDialog(this, resp.message, "Thành công", JOptionPane.INFORMATION_MESSAGE);
                new LoginFrame().setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, resp.message, "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        jplUser = new javax.swing.JPanel();
        lblUser = new javax.swing.JLabel();
        jtbUser = new javax.swing.JTextField();
        jplPass = new javax.swing.JPanel();
        lblPass = new javax.swing.JLabel();
        jpfPass = new javax.swing.JPasswordField();
        lblShowPass = new javax.swing.JLabel();
        jplUser1 = new javax.swing.JPanel();
        lblEmail = new javax.swing.JLabel();
        jtbEmail = new javax.swing.JTextField();
        lblAvatar = new javax.swing.JLabel();
        btnDangKy = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lblDangNhap = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(642, 362));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitle.setText("Đăng ký tài khoản");

        jplUser.setBackground(new java.awt.Color(245, 245, 245));
        jplUser.setPreferredSize(new java.awt.Dimension(315, 38));

        lblUser.setBackground(new java.awt.Color(245, 245, 245));
        lblUser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jtbUser.setBackground(new java.awt.Color(245, 245, 245));
        jtbUser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtbUser.setBorder(null);

        javax.swing.GroupLayout jplUserLayout = new javax.swing.GroupLayout(jplUser);
        jplUser.setLayout(jplUserLayout);
        jplUserLayout.setHorizontalGroup(
            jplUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplUserLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtbUser, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jplUserLayout.setVerticalGroup(
            jplUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jplUserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jplUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtbUser, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(lblUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jplPass.setBackground(new java.awt.Color(245, 245, 245));
        jplPass.setPreferredSize(new java.awt.Dimension(315, 38));

        lblPass.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jpfPass.setBackground(new java.awt.Color(245, 245, 245));
        jpfPass.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jpfPass.setText("jPasswordField1");
        jpfPass.setBorder(null);
        jpfPass.setPreferredSize(new java.awt.Dimension(64, 26));

        lblShowPass.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblShowPass.setPreferredSize(new java.awt.Dimension(25, 25));

        javax.swing.GroupLayout jplPassLayout = new javax.swing.GroupLayout(jplPass);
        jplPass.setLayout(jplPassLayout);
        jplPassLayout.setHorizontalGroup(
            jplPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplPassLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblPass, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpfPass, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblShowPass, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jplPassLayout.setVerticalGroup(
            jplPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jplPassLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jplPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jpfPass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblShowPass, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jplUser1.setBackground(new java.awt.Color(245, 245, 245));
        jplUser1.setPreferredSize(new java.awt.Dimension(315, 38));

        lblEmail.setBackground(new java.awt.Color(245, 245, 245));
        lblEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jtbEmail.setBackground(new java.awt.Color(245, 245, 245));
        jtbEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtbEmail.setBorder(null);

        javax.swing.GroupLayout jplUser1Layout = new javax.swing.GroupLayout(jplUser1);
        jplUser1.setLayout(jplUser1Layout);
        jplUser1Layout.setHorizontalGroup(
            jplUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplUser1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtbEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jplUser1Layout.setVerticalGroup(
            jplUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jplUser1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jplUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtbEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(lblEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        lblAvatar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        btnDangKy.setBackground(new java.awt.Color(76, 175, 80));
        btnDangKy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDangKy.setForeground(new java.awt.Color(255, 255, 255));
        btnDangKy.setText("Đăng ký");
        btnDangKy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangKyActionPerformed(evt);
            }
        });

        jLabel3.setText("Bạn đã có tài khoản?");

        lblDangNhap.setForeground(new java.awt.Color(65, 105, 225));
        lblDangNhap.setText("Đăng nhập");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(lblAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jplPass, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                    .addComponent(jplUser1, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                    .addComponent(jplUser, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                    .addComponent(btnDangKy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDangNhap)
                        .addGap(92, 92, 92))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTitle)
                        .addGap(75, 75, 75))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jplUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jplUser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jplPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDangKy, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblDangNhap))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDangKyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangKyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDangKyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterFrame().setVisible(true);
            }
        });
    }
    
    private void setupBackground() {
        try {
            URL iconURL = getClass().getResource("/resources/bg.png");
            if (iconURL == null) {
                System.err.println("Không tìm thấy ảnh nền!");
                return;
            }

            ImageIcon bgIcon = new ImageIcon(iconURL);
            backgroundLabel = new JLabel(bgIcon);
            backgroundLabel.setOpaque(true);

            // Chuyển layout sang null để tùy ý định vị
            getContentPane().setLayout(null);

            // Lấy kích thước form login
            int formW = jPanel1.getPreferredSize().width;
            int formH = jPanel1.getPreferredSize().height;

            int padding = 50; 
            backgroundLabel.setBounds(0, 0, formW + padding, formH + padding);
            jPanel1.setBounds(padding / 2, padding / 2, formW, formH);

            jPanel1.setOpaque(true);

            getContentPane().add(backgroundLabel);
            getContentPane().add(jPanel1);

            // Đảm bảo form login nổi trên background
            getContentPane().setComponentZOrder(jPanel1, 0);
            getContentPane().setComponentZOrder(backgroundLabel, 1);

            setSize(backgroundLabel.getWidth(), backgroundLabel.getHeight());
            setLocationRelativeTo(null);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    private void setupLabelIcons() {
        resizeLabelIcon(lblUser, "/resources/user.png");
        resizeLabelIcon(lblEmail, "/resources/email.png");
        resizeLabelIcon(lblPass, "/resources/pass.png");
        resizeLabelIcon(lblAvatar, "/resources/register.png");
        resizeLabelIcon(lblShowPass, "/resources/eye_closed.png");
    }

    private void resizeLabelIcon(JLabel label, String path) {
        try {
            URL iconURL = getClass().getResource(path);
            if (iconURL == null) {
                iconURL = getClass().getResource("/" + path);
                if (iconURL == null) iconURL = getClass().getClassLoader().getResource(path);
            }

            if (iconURL != null) {
                ImageIcon icon = new ImageIcon(iconURL);
                // Lấy kích thước hiện tại của JLabel
                int width = label.getWidth();
                int height = label.getHeight();

                // Nếu label chưa có kích thước (ví dụ khi mới khởi tạo), gán kích thước mặc định
                if (width <= 0) width = 128;
                if (height <= 0) height = 128;

                // Co giãn ảnh theo kích thước của label
                Image scaledImg = icon.getImage().getScaledInstance(width, height, Image.SCALE_SMOOTH);
                label.setIcon(new ImageIcon(scaledImg));
                label.setHorizontalAlignment(SwingConstants.CENTER);
                label.setVerticalAlignment(SwingConstants.CENTER);
            } else {
                System.err.println("Không tìm thấy icon cho label: " + path);
            }
        } catch (Exception e) {
            System.err.println("Lỗi khi load icon cho label: " + path);
            e.printStackTrace();
        }
    }

    private void lblShowPassMouseClicked(java.awt.event.MouseEvent evt) {
        if (showing) {
            jpfPass.setEchoChar('•'); // ẩn mật khẩu
            resizeLabelIcon(lblShowPass, "/resources/eye_closed.png");
        } else {
            jpfPass.setEchoChar((char)0); // hiện mật khẩu
            resizeLabelIcon(lblShowPass, "/resources/eye_open.png");
        }
        showing = !showing;
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangKy;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jpfPass;
    private javax.swing.JPanel jplPass;
    private javax.swing.JPanel jplUser;
    private javax.swing.JPanel jplUser1;
    private javax.swing.JTextField jtbEmail;
    private javax.swing.JTextField jtbUser;
    private javax.swing.JLabel lblAvatar;
    private javax.swing.JLabel lblDangNhap;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblShowPass;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUser;
    // End of variables declaration//GEN-END:variables
}
